services:
  auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: usersdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d usersdb"]
      interval: 10s
      timeout: 5s
      retries: 5
