services:
  auth_service:
    build:
      context: .
      dockerfile: auth_service/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgres_users:
        condition: service_healthy
    environment:
      - JWT_SECRET_KEY
  postgres_users:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: usersdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d usersdb"]
      interval: 10s
      timeout: 5s
      retries: 5
  migrate_users:
    image: gomicro/goose
    command: goose -dir /app/migrations postgres "postgresql://admin:admin@postgres_users:5432/usersdb?sslmode=disable" up
    volumes:
      - ./auth_service/internal/database/migrations:/app/migrations
    depends_on:
      postgres_users:
        condition: service_healthy
