basePath: /
definitions:
  entity.AuthResponse:
    properties:
      id:
        type: string
      message:
        type: string
    type: object
  entity.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  entity.User:
    properties:
      email:
        example: user_1234@gmail.com
        type: string
      id:
        example: "1234"
        type: string
      password:
        example: pass_1234
        type: string
      phone:
        example: "89178298123"
        type: string
      username:
        example: user_1234
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the auth service of course project
  title: Auth Service
paths:
  /login:
    post:
      consumes:
      - application/json
      description: login user by credentials
      parameters:
      - description: user to login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: Login user
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      description: register user by credentials
      parameters:
      - description: user to register
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: Register user
      tags:
      - auth
swagger: "2.0"
