definitions:
  entity.AuthResponse:
    properties:
      id:
        type: string
      message:
        type: string
    type: object
  entity.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  entity.User:
    properties:
      email:
        example: user_1234@gmail.com
        type: string
      id:
        example: "1234"
        type: string
      password:
        example: pass_1234
        type: string
      phone:
        example: "89178298123"
        type: string
      username:
        example: user_1234
        type: string
    type: object
  handlers.codeInput:
    properties:
      code:
        type: string
      email:
        type: string
    type: object
  handlers.inputRecovery:
    properties:
      email:
        type: string
    type: object
  handlers.passwordInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
  description: This is the auth services of course project
  title: Auth Service
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: login user by credentials
      parameters:
      - description: user to login
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: Login user
      tags:
      - auth
  /auth/logout:
    post:
      consumes:
      - application/json
      description: logout user with token's validation
      produces:
      - application/json
      responses:
        "200":
          description: Token is valid
          schema:
            type: nil
        "400":
          description: Invalid token is sent
          schema:
            type: nil
        "401":
          description: User is unauthorized
          schema:
            type: nil
      security:
      - BearerAuth: []
      summary: Logout user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: register user by credentials
      parameters:
      - description: user to register
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entity.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/entity.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entity.ErrorResponse'
      summary: Register user
      tags:
      - auth
  /password/request-reset:
    post:
      consumes:
      - application/json
      description: recover your password by email code
      parameters:
      - description: email of the user
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/handlers.inputRecovery'
      produces:
      - application/json
      responses:
        "200":
          description: code was sent
          schema:
            type: nil
        "400":
          description: invalid email
          schema:
            type: nil
      summary: Recover password
      tags:
      - recovery
  /password/reset:
    post:
      consumes:
      - application/json
      description: update password for registered user
      parameters:
      - description: password and email of the user for recovery
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/handlers.passwordInput'
      responses:
        "200":
          description: password is valid
          schema:
            type: nil
        "400":
          description: invalid code
          schema:
            type: nil
      summary: Reset Password
      tags:
      - recovery
  /password/validate-code:
    post:
      consumes:
      - application/json
      description: compare passed code with the saved one
      parameters:
      - description: code and email of the user for recovery
        in: body
        name: code
        required: true
        schema:
          $ref: '#/definitions/handlers.codeInput'
      produces:
      - application/json
      responses:
        "200":
          description: code is valid
          schema:
            type: nil
        "400":
          description: invalid code
          schema:
            type: nil
      summary: Validate Code
      tags:
      - recovery
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
